# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: OMG3DP!
description: Adventures in 3D Printing
email: hello@maxglenister.co.uk
author: Max Glenister
author-bio:  This website is a collection of all of the things I've been doing with my 3D Printer. <br><br>You'll find lots of examples of badly modelled things, poorly printed things, and a lot of wasted plastic!
avatar: assets/images/avatar.jpg

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social settings
github: omgmog
twitter: omgmog
thingiverse: omgmog
website: "https://omgmog.net"
blog: "https://blog.omgmog.net"

# Google Analytics Tracking ID goes here:
ga_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge



paginate: 100
paginate_path: "/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - rouge

sass:
  sass_dir: _scss
  style: :compressed


defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
      classes: post
